---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: citadel
  name: challenger-job-migrate-${BUILD_ID}
  labels:
    app: challenger
    onfinish: "destroy"
    env: ${QUANTUM_DEPLOYMENT_ENV}
    deployment: ${QUANTUM_DEPLOYMENT_NAME}
spec:
  template:
    metadata:
      labels:
        app: challenger
        onfinish: "destroy"
        env: ${QUANTUM_DEPLOYMENT_ENV}
        deployment: ${QUANTUM_DEPLOYMENT_NAME}
    spec:
      restartPolicy: Never
      imagePullSecrets:
      - name: dockerhub.wizards
      containers:
      - image: wizardsofindustry/quantum-challenger:${IMAGE_TAG}
        name: challenger-job-migrate
        command:
        - "alembic"
        - "upgrade"
        - "head"
        env:
        - name: CHALLENGER_RDBMS_DSN
          valueFrom:
            secretKeyRef:
              key: dsn
              name: rdbms.challenger
        - name: CHALLENGER_ROLE
          value: default
        - name: CHALLENGER_ROLE
          value: default
        - name: CHALLENGER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: application.secret.challenger
        - name: QUANTUM_DEPLOYMENT_ENV
          value: ${QUANTUM_DEPLOYMENT_ENV}
        - name: QUANTUM_DEPLOYMENT_NAME
          value: ${QUANTUM_DEPLOYMENT_NAME}
        envFrom:
        - configMapRef:
            name: config.common.challenger
        - configMapRef:
            name: config.${QUANTUM_DEPLOYMENT_ENV}.challenger
  activeDeadlineSeconds: 120
  restartPolicy: Never
  parallelism: 1
  completions: 1
