"""initial revision

Revision ID: 59fe5943afd6
Revises: 
Create Date: 2018-08-11 21:14:03.726541

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = '59fe5943afd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonenumberchallenges',
    sa.Column('phonenumber', sa.String(), nullable=False),
    sa.Column('challenged', sa.BigInteger(), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('using', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phonenumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumberchallenges')
    # ### end Alembic commands ###
