"""Initial revision

Revision ID: b2bf95405495
Revises: 
Create Date: 2018-08-11 21:54:26.876384

"""
from alembic import op
import sqlalchemy as sa
import sq.ext.rdbms.types


# revision identifiers, used by Alembic.
revision = 'b2bf95405495'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phonenumberchallenges',
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('challenged', sa.BigInteger(), nullable=False),
    sa.Column('expires', sa.BigInteger(), nullable=False),
    sa.Column('using', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('recipient')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumberchallenges')
    # ### end Alembic commands ###
